# Databricks notebook source
# MAGIC %md
# MAGIC # Setup: Synthetic Parcel & Delivery Data
# MAGIC
# MAGIC Generates the catalog, schema, and Delta tables that the Route Optimizer
# MAGIC Accelerator depends on. Run once.
# MAGIC
# MAGIC Tables produced in `${catalog}.${schema}` (default
# MAGIC `supplychain.route_optimizer_accelerator`):
# MAGIC
# MAGIC | Table | Approx rows | Purpose |
# MAGIC |---|---|---|
# MAGIC | `depot` | 1 | Central distribution hub (route start/end) |
# MAGIC | `customers` | ~40 | Delivery accounts clustered around a metro |
# MAGIC | `parcels` | ~40 | Stops to route: demand + ready/due time window |
# MAGIC
# MAGIC Deterministic: `random.seed(42)`. Some `due_minute` windows are made tight
# MAGIC on purpose so the CVRPTW time constraints actually bite when the solver
# MAGIC runs when Genie calls `optimize_routes`.

# COMMAND ----------

dbutils.widgets.text("catalog", "supplychain", "Catalog")
dbutils.widgets.text("schema", "route_optimizer_accelerator", "Schema")

CATALOG = dbutils.widgets.get("catalog")
SCHEMA = dbutils.widgets.get("schema")

spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA}")
spark.sql(f"USE {CATALOG}.{SCHEMA}")

print(f"Writing into {CATALOG}.{SCHEMA}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. Static reference data — depot, customers, vehicles
# MAGIC
# MAGIC Customers are generated by clustering small offsets around a handful of
# MAGIC metro hubs. The result is realistic geographic density that a CVRPTW
# MAGIC solver actually has to think about — most customers cluster near the
# MAGIC central depot, with a few intentionally-distant accounts to expose the
# MAGIC routing trade-offs.

# COMMAND ----------

import random
from datetime import date, timedelta

from pyspark.sql import Row

random.seed(42)

DEPOT_LAT, DEPOT_LON = 29.7604, -95.3698  # Central distribution hub (Houston metro)

HUBS = [
    # (hub_label, lat, lon, customer_count, offset_deg)
    # All hubs reachable round-trip from the central depot inside an 8h shift.
    ("Houston TX",    29.7604, -95.3698, 6, 0.08),
    ("Pasadena TX",   29.6911, -95.2091, 5, 0.06),
    ("Baytown TX",    29.7355, -95.0118, 4, 0.07),
    ("La Porte TX",   29.6658, -95.0192, 4, 0.06),
    ("Sugar Land TX", 29.5994, -95.6144, 4, 0.07),
    ("Conroe TX",     30.3119, -95.4561, 4, 0.07),
    ("Texas City TX", 29.3838, -94.9027, 4, 0.07),
    ("Galveston TX",  29.3013, -94.7977, 3, 0.07),
    ("Freeport TX",   28.9541, -95.3597, 3, 0.07),
    ("Beaumont TX",   30.0860, -94.1018, 3, 0.07),
]

ADJECTIVES = [
    "Apex", "Atlas", "Beacon", "Cardinal", "Constellation", "Crest",
    "Forge", "Frontier", "Granite", "Horizon", "Ironwood", "Keystone",
    "Meridian", "Northstar", "Olympus", "Patriot", "Pioneer", "Polaris",
    "Sentinel", "Sequoia", "Sterling", "Stratos", "Summit", "Vanguard",
    "Vector", "Zenith",
]
PLACE_QUALIFIERS = ["", "", "North", "South", "East", "West", "Ridge", "Field", "Plains", "Basin"]
ENTITIES = [
    "Retail", "Trading", "Distribution", "Wholesale", "Commerce",
    "Mercantile", "Outfitters", "Goods", "Supply", "Provisions",
    "Marketplace", "Boutique", "Depot", "Emporium",
]

DEPOT_ID = 1

# Build a deterministic set of customer names across the hubs.
used_names: set[str] = set()
CUSTOMERS: list[Row] = []
customer_id_seq = 0
for hub_label, hub_lat, hub_lon, count, offset in HUBS:
    city = hub_label.rsplit(" ", 1)[0]
    state = hub_label.rsplit(" ", 1)[1]
    for _ in range(count):
        for _attempt in range(40):
            adj = random.choice(ADJECTIVES)
            qual = random.choice(PLACE_QUALIFIERS)
            ent = random.choice(ENTITIES)
            name = " ".join(p for p in (adj, qual, ent) if p)
            if name not in used_names:
                used_names.add(name)
                break
        customer_id_seq += 1
        lat = hub_lat + random.uniform(-offset, offset)
        lon = hub_lon + random.uniform(-offset, offset)
        CUSTOMERS.append(
            Row(
                customer_id=customer_id_seq,
                customer_name=name,
                lat=lat,
                lon=lon,
                city=city,
                state=state,
            )
        )

print(f"Generated {len(CUSTOMERS)} customers across {len(HUBS)} hubs")

# COMMAND ----------

def _write(df, name: str) -> None:
    df.write.mode("overwrite").option("overwriteSchema", "true").saveAsTable(name)


depot = spark.createDataFrame(
    [Row(depot_id=DEPOT_ID, name="Central Distribution Hub", lat=DEPOT_LAT, lon=DEPOT_LON)]
)
_write(depot, "depot")

customers = spark.createDataFrame(CUSTOMERS)
_write(customers, "customers")

print(f"Wrote depot (1), customers ({len(CUSTOMERS)})")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. Parcels — the stops to route
# MAGIC
# MAGIC One parcel per customer for today's run. Each parcel carries:
# MAGIC
# MAGIC - `demand_units` — small integer payload (van capacity is 100 units).
# MAGIC - `ready_minute` — earliest the stop can be served (most are 0 = shift start).
# MAGIC - `due_minute` — deadline inside the 0–480 (8h) shift. We deliberately
# MAGIC   assign **tight windows to ~30% of parcels** (morning / early-afternoon
# MAGIC   deadlines) so the time-window dimension constrains the solution; the
# MAGIC   rest are due anytime in the shift.
# MAGIC
# MAGIC The `optimize_routes` TVF filters these rows by depot and horizon at query time.

# COMMAND ----------

SHIFT_MINUTES = 480  # 8h delivery shift

# Urgency tiers -> due_minute. Tight tiers make the time constraints bite.
URGENCY_TIERS = [
    ("rush_morning", 240),   # must finish before mid-morning cutoff
    ("midday",       360),   # by early afternoon
    ("afternoon",    SHIFT_MINUTES),  # anytime in the shift
    ("afternoon",    SHIFT_MINUTES),  # weight the "anytime" bucket heavier
]

CREATED = date.today()

PARCELS: list[Row] = []
parcel_id_seq = 0
for c in CUSTOMERS:
    parcel_id_seq += 1
    demand = random.choice([5, 8, 10, 12, 15, 18, 20, 25, 30])
    tier, due = random.choice(URGENCY_TIERS)
    # A handful of parcels are not available until partway through the shift.
    ready = random.choice([0, 0, 0, 0, 30, 60, 90])
    # Keep windows coherent: a parcel can't be due before it's ready.
    if due <= ready:
        due = min(SHIFT_MINUTES, ready + 120)
    PARCELS.append(
        Row(
            parcel_id=parcel_id_seq,
            customer_id=c.customer_id,
            depot_id=DEPOT_ID,
            demand_units=demand,
            ready_minute=ready,
            due_minute=due,
            created_date=CREATED,
        )
    )

parcels = spark.createDataFrame(PARCELS)
_write(parcels, "parcels")

tight = sum(1 for p in PARCELS if p.due_minute < SHIFT_MINUTES)
print(
    f"Wrote {len(PARCELS)} parcels "
    f"({tight} with tight due windows, {len(PARCELS) - tight} due anytime in shift)"
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. Sanity checks

# COMMAND ----------

for tbl in ["depot", "customers", "parcels"]:
    cnt = spark.table(tbl).count()
    print(f"{tbl:<12} {cnt:>5} rows")

# COMMAND ----------

display(spark.sql("""
    SELECT
      p.parcel_id, c.customer_name, c.city, c.state,
      p.demand_units, p.ready_minute, p.due_minute
    FROM parcels p
    JOIN customers c USING (customer_id)
    ORDER BY p.due_minute, p.parcel_id
    LIMIT 15
"""))
